version: '3'

services:
  fast-server:
    build:
      context: .
      dockerfile: Dockerfile-fast
    volumes:
      - .:/code
    ports:
      - '8000:8000'
    expose:
      - '8000'
    restart: unless-stopped
    depends_on:
      - pocketbase
    command: uvicorn src.fast_server:app --host 0.0.0.0 --port 8000
  pocketbase:
    build:
      context: .
      dockerfile: Dockerfile-pb
    ports:
      - '8080:8080'
    expose:
      - '8080'
    restart: unless-stopped
    volumes:
      - pocketbase-data:/pb_data
    command: /pb/pocketbase serve --http=0.0.0.0:8080

volumes:
  pocketbase-data:
